### PR TITLE
defines nxt_cpu_pause for ARM64

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
Hello David!

Would you mind adding some information to the commit message pointing to documentation of `__asm__("yield")` and maybe describing it a bit?  Why `"yield"`?  I don't know about ARM64 asm, and would like to be able to review the patch.  Thanks!

Cheers,

Alex

**Comment by ac000** [comment]
This [SO](https://stackoverflow.com/questions/70810121/why-does-hintspin-loop-use-isb-on-aarch64) suggests `isb` may be a better instruction to use on aarch64...

**Comment by devnexen** [comment]
Yes it is indeed, my knowledge of arm64 had grown since :-)

**Review by ac000 — APPROVED** [review]
LGTM. Thanks.

Just needed some tweaking to fit with current style.

**Comment by ac000** [comment]
This was merged as https://github.com/nginx/unit/commit/dfdf948f899bda9120750d28c1be32f255ed941f

Sorry this took so long!

**Pull request closed without merging**
