### PR TITLE
Added join link for slack community

### PR DESCRIPTION
**Pull request by tarynmusgrave**
Added a join link for the slack community to `CONTRIBUTING.md`

### CODE REVIEW

**Comment by ac000** [comment]
Out of curiosity (though not so curious that I actually want to do it!) what happens if you actually hit the 'Submit' button?

**Comment by tarynmusgrave** [comment]
> Out of curiosity (though not so curious that I actually want to do it!) what happens if you actually hit the 'Submit' button?

Well I hoped it sent a message to @dwmcallister to give me access to the slack group. 

Is there an opportunity to automate access?

**Comment by lcrilly** [comment]
We decided to retire the Community Slack for Unit now that we have GitHub discussions open
https://nginxcommunity.slack.com/archives/C02SS9UB85C/p1702415320858979

@tippexs wrote there:
> I know this channel is great BUT we are moving our development workflows to GitHub. Therefore all the discussions and question should be asked in our GitHub repositories Discussions.
> https://github.com/nginx/unit/discussions
> Why?
> Github Discussions are searchable through search engines like google and Issues / PRs can be easily be linked.
> We are really looking forward seeing you on the other side! The plans for the next year are BIG and I can't wait to get your input about them!
> Thank you for all your interest and contribution to the Unit project!

**Comment by tarynmusgrave** [comment]
Perfect. Ill change this PR to reference Github discussions instead :)

**Comment by ac000** [comment]
Is it still useful then to have a pointer to the slack channel?, it seems you can't access it without an account anyway..

**Comment by lcrilly** [comment]
I'm expecting the next PR to reference GitHub discussions and remove reference to Slack. I think that's what @tarynmusgrave is suggesting.

It would be excellent to do the same for the README.md (not just CONTRIBUTING.md).

**Comment by tippexs** [comment]
I am on it! I will change this and submit the PR right away. Thanks @lcrilly

**Comment by tarynmusgrave** [comment]
> I'm expecting the next PR to reference GitHub discussions and remove reference to Slack. I think that's what @tarynmusgrave is suggesting.
> 
> It would be excellent to do the same for the README.md (not just CONTRIBUTING.md).

Yup, that is what I am suggesting :) I will update them both today.

**Comment by tarynmusgrave** [comment]
> I am on it! I will change this and submit the PR right away. Thanks @lcrilly

I got it, Thanks @tippexs

**Pull request closed without merging**
