### PR TITLE
Fix build with wasmtime 27.0.0

### PR DESCRIPTION
**Pull request by osokin**

### CODE REVIEW

**Comment by thresheek** [comment]
Does that still work with e.g. wasmtime 24?

**Comment by thresheek** [comment]
> Does that still work with e.g. wasmtime 24?

Ah, it looks like CI tells us it does not: https://github.com/nginx/unit/actions/runs/11979528350/job/33401907630?pr=1493

**Comment by ac000** [comment]
I guess we also want write perms to match current behaviour...

**Comment by osokin** [comment]
> I guess we also want write perms to match current behaviour...

Updated.

**Review by ac000 — APPROVED** [review]

**Comment by ac000** [comment]
Merged. Thanks Sergey!

**Pull request merged**
