### PR TITLE
wasm-wc: Update to wasmtime 27.0.0

### PR DESCRIPTION
**Pull request by ac000**
For no real reason other than to be on the latest release for the next release of Unit...

### CODE REVIEW

**Comment by ac000** [comment]
**NOTE:** `Cargo.lock` was updated automatically...

**Comment by callahad** [comment]
We can probably omit the commit message body, or at least the "For now real reason" part.

The expectation in the Rust and Wasm communities would be that we're regularly bumping our dependencies.

**Comment by ac000** [comment]
It's just to highlight it wasn't for a bugfix/security related reason...

**Comment by callahad** [comment]
Your commit, your message :) Fire away as you see fit

**Comment by ac000** [comment]
Rebased with master

```
$ git range-diff 5bce2af0...f5371e95
-:  -------- > 1:  9e98a7e5 Docker: update Python and PHP versions
-:  -------- > 2:  655ca61b Packages: support rpm 4.20+
-:  -------- > 3:  19f403f5 Packages: add Fedora 41 support
-:  -------- > 4:  ae20ab0a auto/otel: Remove pkg-config check
1:  5bce2af0 = 5:  f5371e95 wasm-wc: Update to wasmtime 27.0.0
```

**Pull request merged**
