### PR TITLE
Switch nxt_bool_t to uint8_t and use it in structs

### PR DESCRIPTION
**Pull request by ac000**
This pull request covers the work ro change our nxt_bool_t from an unsigned int to a uint8_t and make use of it in structures where it will be much more intuitive.

Patch overview

These remove a bunch of unused code, no point messing around changing
and checking code which is never getting used.

-  Remove a bunch of dead code.
-  Remove an unused structure.

We need to do a couple of fixups

-  Use unsigned int for nxt_bool_t in va_arg().
-  Don't conflate the error variable in nxt_kqueue_poll().

We then get to the main part, switching nxt_bool_t to a uint8_t, this is
what we were able to agree on at the time. If we do go to _Bool at some
point then it's essentially a one line change.

-  Change nxt_bool_t from a nxt_uint_t to a uint8_t.

We then gradually introduce the structure and config changes...

-  Change nxt_bool_t from a nxt_uint_t to a uint8_t.                             
-  Convert uint8_t struct boolean members to nxt_bool_t.                         
-  Convert uint32_t struct boolean members to nxt_bool_t.                        
-  Add NXT_CONF_MAP_BOOL.                                                        
-  Use NXT_CONF_MAP_BOOL.                                                        
-  Remove NXT_CONF_MAP_INT8.                                                     
-  Remove an erroneous semi-colon.                                               
-  Use nxt_bool_t in the configuration type system.

### CODE REVIEW

**Comment by ac000** [comment]
In [struct nxt_runtime_s](https://github.com/nginx/unit/blob/master/src/nxt_runtime.h#L54-L57) we have the following members

```c
    uint8_t                daemon;                                              
    uint8_t                batch;                                               
    uint8_t                status;                                              
    uint8_t                is_pid_isolated;
```

**daemon** and **is_pid_isolated** certainly seem to be booleans, (though they are missing the 1 bit comment), not sure about the other two. Oh well, this only strengthens the case for this patchset...

**Comment by alejandro-colomar** [comment]
Here's another thread we could pull:

```c
$ grep -rnC2 ':1;' src/
src/test/nxt_http_parse_test.c-16-
src/test/nxt_http_parse_test.c-17-    /* target with "/." */
src/test/nxt_http_parse_test.c:18:    unsigned   complex_target:1;
src/test/nxt_http_parse_test.c-19-    /* target with "%" */
src/test/nxt_http_parse_test.c:20:    unsigned   quoted_target:1;
src/test/nxt_http_parse_test.c-21-    /* target with " " */
src/test/nxt_http_parse_test.c:22:    unsigned   space_in_target:1;
src/test/nxt_http_parse_test.c-23-} nxt_http_parse_test_request_line_t;
src/test/nxt_http_parse_test.c-24-
--
src/test/nxt_http_parse_test.c-26-typedef struct {
src/test/nxt_http_parse_test.c-27-    nxt_int_t  result;
src/test/nxt_http_parse_test.c:28:    unsigned   discard_unsafe_fields:1;
src/test/nxt_http_parse_test.c-29-} nxt_http_parse_test_fields_t;
src/test/nxt_http_parse_test.c-30-
--
src/nxt_websocket_header.h-12-typedef struct {
src/nxt_websocket_header.h-13-#if (NXT_HAVE_BIG_ENDIAN)
src/nxt_websocket_header.h:14:    uint8_t fin:1;
src/nxt_websocket_header.h:15:    uint8_t rsv1:1;
src/nxt_websocket_header.h:16:    uint8_t rsv2:1;
src/nxt_websocket_header.h:17:    uint8_t rsv3:1;
src/nxt_websocket_header.h-18-    uint8_t opcode:4;
src/nxt_websocket_header.h-19-
src/nxt_websocket_header.h:20:    uint8_t mask:1;
src/nxt_websocket_header.h-21-    uint8_t payload_len:7;
src/nxt_websocket_header.h-22-#endif
--
src/nxt_websocket_header.h-24-#if (NXT_HAVE_LITTLE_ENDIAN)
src/nxt_websocket_header.h-25-    uint8_t opcode:4;
src/nxt_websocket_header.h:26:    uint8_t rsv3:1;
src/nxt_websocket_header.h:27:    uint8_t rsv2:1;
src/nxt_websocket_header.h:28:    uint8_t rsv1:1;
src/nxt_websocket_header.h:29:    uint8_t fin:1;
src/nxt_websocket_header.h-30-
src/nxt_websocket_header.h-31-    uint8_t payload_len:7;
src/nxt_websocket_header.h:32:    uint8_t mask:1;
src/nxt_websocket_header.h-33-#endif
src/nxt_websocket_header.h-34-
--
src/nxt_unit_field.h-22-struct nxt_unit_field_s {
src/nxt_unit_field.h-23-    uint16_t              hash;
src/nxt_unit_field.h:24:    uint8_t               skip:1;
src/nxt_unit_field.h:25:    uint8_t               hopbyhop:1;
src/nxt_unit_field.h-26-    uint8_t               name_length;
src/nxt_unit_field.h-27-    uint32_t              value_length;
--
src/nxt_timer.h-29-
src/nxt_timer.h-30-    uint16_t                  change:14;
src/nxt_timer.h:31:    uint16_t                  enabled:1;
src/nxt_timer.h:32:    uint16_t                  queued:1;
src/nxt_timer.h-33-
src/nxt_timer.h-34-    nxt_msec_t                time;
--
src/nxt_http_parse.h-86-struct nxt_http_field_s {
src/nxt_http_parse.h-87-    uint16_t                  hash;
src/nxt_http_parse.h:88:    uint8_t                   skip:1;
src/nxt_http_parse.h:89:    uint8_t                   hopbyhop:1;
src/nxt_http_parse.h-90-    uint8_t                   name_length;
src/nxt_http_parse.h-91-    uint32_t                  value_length;
--
src/nxt_fd_event.h-70-    uint8_t                   closed;
src/nxt_fd_event.h-71-    uint8_t                   timedout;
src/nxt_fd_event.h:72:    uint8_t                   shutdown:1;
src/nxt_fd_event.h-73-#if (NXT_HAVE_EPOLL)
src/nxt_fd_event.h:74:    uint8_t                   epoll_eof:1;
src/nxt_fd_event.h:75:    uint8_t                   epoll_error:1;
src/nxt_fd_event.h-76-#endif
src/nxt_fd_event.h-77-#if (NXT_HAVE_KQUEUE)
src/nxt_fd_event.h:78:    uint8_t                   kq_eof:1;
src/nxt_fd_event.h-79-#endif
src/nxt_fd_event.h-80-
--
src/nxt_fd_event.h-82-    nxt_fd_event_state_t      read:3;
src/nxt_fd_event.h-83-    nxt_fd_event_state_t      write:3;
src/nxt_fd_event.h:84:    uint8_t                   read_ready:1;
src/nxt_fd_event.h:85:    uint8_t                   write_ready:1;
src/nxt_fd_event.h:86:    uint8_t                   changing:1;
src/nxt_fd_event.h:87:    uint8_t                   closed:1;
src/nxt_fd_event.h:88:    uint8_t                   timedout:1;
src/nxt_fd_event.h:89:    uint8_t                   shutdown:1;
src/nxt_fd_event.h-90-#if (NXT_HAVE_EPOLL)
src/nxt_fd_event.h:91:    uint8_t                   epoll_eof:1;
src/nxt_fd_event.h:92:    uint8_t                   epoll_error:1;
src/nxt_fd_event.h-93-#endif
src/nxt_fd_event.h-94-#if (NXT_HAVE_KQUEUE)
src/nxt_fd_event.h:95:    uint8_t                   kq_eof:1;
src/nxt_fd_event.h-96-#endif
src/nxt_fd_event.h-97-#endif /* NXT_64BIT */
--
src/nxt_buf.h-80-    uint8_t                 cache_hint;
src/nxt_buf.h-81-
src/nxt_buf.h:82:    uint8_t                 is_file:1;
src/nxt_buf.h:83:    uint8_t                 is_mmap:1;
src/nxt_buf.h:84:    uint8_t                 is_port_mmap:1;
src/nxt_buf.h:85:    uint8_t                 is_sync:1;
src/nxt_buf.h:86:    uint8_t                 is_nobuf:1;
src/nxt_buf.h:87:    uint8_t                 is_flush:1;
src/nxt_buf.h:88:    uint8_t                 is_last:1;
src/nxt_buf.h:89:    uint8_t                 is_port_mmap_sent:1;
src/nxt_buf.h:90:    uint8_t                 is_ts:1;
src/nxt_buf.h-91-
src/nxt_buf.h-92-    nxt_buf_mem_t           mem;
--
src/nxt_http_route_addr.h-47-typedef struct {
src/nxt_http_route_addr.h-48-    uint8_t       match_type:2;
src/nxt_http_route_addr.h:49:    uint8_t       negative:1;
src/nxt_http_route_addr.h-50-    uint8_t       addr_family;
src/nxt_http_route_addr.h-51-
```

Most of these should be bools.

**Comment by ac000** [comment]
Ah yeas, I forgot about those cases.

I'd leave the websocket ones as is. The others would need double checking.

**Comment by ac000** [comment]
Maybe someday... (some of the non-bool conversion patches were applied).

**Pull request closed without merging**
