### PR TITLE
Packages: fixed a path to python 3.12 example app

### PR DESCRIPTION
**Pull request by thresheek**

### CODE REVIEW

**Comment by ac000** [comment]
No need for a trailing `.` on the subject line.

**Comment by thresheek** [comment]
> No need for a trailing `.` on the subject line.

Sounds like we have a good candidate for CI pre-compile check!

(Thanks, I'll fix it)

**Comment by thresheek** [comment]
Dot removed from the commit line, thanks!

**Review by callahad — APPROVED** [review]

**Comment by callahad** [comment]
Matches other rpmbuild examples. Merging.

**Pull request merged**
