### PR TITLE
njs: compatibility with 0.8.5

### PR DESCRIPTION
**Pull request by andrey-zelenkov**
njs changed strings API so now instead of `njs_vm_value_string_set()` used `njs_vm_value_string_create()` as a drop-in replacement. 

For more information see:
http://hg.nginx.org/njs/rev/4e0553f7ea68

### CODE REVIEW

**Comment by hongzhidao** [comment]
LGTM.

**Comment by hongzhidao** [comment]
I'd suggest waiting for it until the next njs version is released, perhaps there are more changed APIs.

**Comment by callahad** [comment]
For context, [the current release is 0.8.4](https://github.com/nginx/njs/tags) so we're waiting for something 0.8.5 to get tagged.

**Review by ac000 — COMMENTED** [review]
Can we wrap the message after 72 chars please.

Also I'd just make the link a `Link:` tag... so something like this

```
contrib: updated njs to 0.8.5

njs changed strings API so now instead of njs_vm_value_string_set() used
njs_vm_value_string_create() as a drop-in replacement.

Link: <https://github.com/nginx/njs/commit/5730d5ffe23a4965c001d873695d22005fcfa588>
```

**Comment by andrey-zelenkov** [comment]
Commit message:

```
% git range-diff  02e8afa0...e57e7fcc
1:  02e8afa0 ! 1:  e57e7fcc contrib: updated njs to 0.8.5
    @@ Metadata
      ## Commit message ##
         contrib: updated njs to 0.8.5
     
    -    njs changed strings API so now instead of njs_vm_value_string_set() used njs_vm_value_string_create() as a drop-in replacement.
    +    njs changed strings API so now instead of njs_vm_value_string_set() used
    +    njs_vm_value_string_create() as a drop-in replacement.
     
    -    For more information see:
    -    https://github.com/nginx/njs/commit/5730d5ffe23a4965c001d873695d22005fcfa588
    +    Link: <https://github.com/nginx/njs/commit/5730d5ffe23a4965c001d873695d22005fcfa588>
     
      ## pkg/contrib/src/njs/SHA512SUMS ##
     @@
```

**Review by ac000 — APPROVED** [review]
I would probably put the package changes in their own commit, but I won't block this on that in this case...

**Pull request merged**
