### PR TITLE
Docker-related updates

### PR DESCRIPTION
**Pull request by thresheek**
This patchset adds pre-release docker-related changes:

- Bumped Go versions
- Updated Rust version used in Dockerfiles
- Introduced "slim" Python images
- Make build-% targets create files to track if builds succeded or not

### CODE REVIEW

**Review by ac000 — COMMENTED** [review]
```
Docker: introduced "slim" python images.

Closes: https://github.com/nginx/unit/issues/1352
```

Subject can simply be (imperative mood, no trailing period)

```
Docker: introduce "slim" python images
```

**Review by ac000 — COMMENTED** [review]
`Docker: updated Rust version` -> `Docker: update Rust version`

**Review by ac000 — APPROVED** [review]
Other than the minor things... LGTM

**Comment by thresheek** [comment]
Thanks for the review!  Commit messages changed as requested.

**Pull request merged**
