### PR TITLE
1.33.0 Release Preparations

### PR DESCRIPTION
**Pull request by ac000**
This is a preparatory branch for the 1.33.0 release.

### CODE REVIEW

**Comment by ac000** [comment]
- Add @avahahn 's unitcl changelog entry (slightly re-worded)
- Capitalise 'Unit'

```
$ git range-diff a09484b3...786b8e0f
1:  8f39173f ! 1:  ba03644c docs/changes.xml: Add 1.33.0 changelog entries
    @@ docs/changes.xml: NGINX Unit updated to 1.33.0.
     +</para>
     +</change>
     +
    ++<change type="feature">
    ++<para>
    ++Unit ships with a new Rust based CLI application "unitctl".
    ++</para>
    ++</change>
    ++
     +<change type="change">
     +<para>
     +under systemd unit runs in forking mode (once again).
    @@ docs/changes.xml: NGINX Unit updated to 1.33.0.
      
     +<change type="change">
     +<para>
    -+unit now builds with -std=gnu11 (C11 with GNU extensions).
    ++Unit now builds with -std=gnu11 (C11 with GNU extensions).
     +</para>
     +</change>
     +
     +<change type="change">
     +<para>
    -+unit now creates the full directory path for the PID file and control socket.
    ++Unit now creates the full directory path for the PID file and control socket.
     +</para>
     +</change>
     +
2:  a09484b3 ! 2:  786b8e0f Add 1.33.0 CHANGES
    @@ Metadata
      ## Commit message ##
         Add 1.33.0 CHANGES
     
    +    This is autogenerated from docs/changes.xml by
    +
    +      $ make -C docs/ changes
    +
         Signed-off-by: Andrew Clayton <a.clayton@nginx.com>
     
      ## CHANGES ##
     @@
      
    -+Changes with Unit 1.33.0                                         22 Aug 2024
    ++Changes with Unit 1.33.0                                         23 Aug 2024
     +
     +    *) Feature: show list of loaded language modules in the /status
     +       endpoint.
    @@ CHANGES
     +
     +    *) Feature: add "if" option to the "match" object.
     +
    ++    *) Feature: Unit ships with a new Rust based CLI application "unitctl".
    ++
     +    *) Change: under systemd unit runs in forking mode (once again).
     +
     +    *) Change: if building with njs, version 0.8.3 or later is now required.
     +
    -+    *) Change: unit now builds with -std=gnu11 (C11 with GNU extensions).
    ++    *) Change: Unit now builds with -std=gnu11 (C11 with GNU extensions).
     +
    -+    *) Change: unit now creates the full directory path for the PID file and
    ++    *) Change: Unit now creates the full directory path for the PID file and
     +       control socket.
     +
     +    *) Change: build system improvements, including pretty printing the make
```

@avahahn 

If you're happy with the slight change I made (mostly to reflect that unit already has some CLI tools..)

Then can you OK my adding

```
Co-developed-by: Ava Hahn <a.hahn@f5.com>                                       
Signed-off-by: Ava Hahn <a.hahn@f5.com>
```
to
```
commit ba03644c8d6f0d7b7c1dac30b8966bc9045c34ac
Author: Andrew Clayton <a.clayton@nginx.com>
Date:   Thu Aug 22 22:30:12 2024 +0100

    docs/changes.xml: Add 1.33.0 changelog entries
    
    Signed-off-by: Andrew Clayton <a.clayton@nginx.com>
```

**Comment by ac000** [comment]
Add wasm-wasi-component environment inheritance to the chagelog

``` 
$ git range-diff c21c208f...77509455
1:  52bf99f5 ! 1:  de787ddc docs/changes.xml: Add 1.33.0 changelog entries
    @@ docs/changes.xml: NGINX Unit updated to 1.33.0.
     +</para>
     +</change>
     +
    ++<change type="feature">
    ++<para>
    ++the wasm-wasi-component language module now inherits the processes
    ++environment.
    ++</para>
    ++</change>
    ++
     +<change type="change">
     +<para>
     +under systemd unit runs in forking mode (once again).
2:  c21c208f ! 2:  77509455 Add 1.33.0 CHANGES
    @@ Commit message
     
         This is autogenerated from docs/changes.xml by
     
    -      $ make -C docs/ changes
    +      $ make -C docs/ changes && mv build/CHANGES .
     
         Signed-off-by: Andrew Clayton <a.clayton@nginx.com>
     
      ## CHANGES ##
     @@
      
    -+Changes with Unit 1.33.0                                         23 Aug 2024
    ++Changes with Unit 1.33.0                                         04 Sep 2024
     +
     +    *) Feature: show list of loaded language modules in the /status
     +       endpoint.
    @@ CHANGES
     +
     +    *) Feature: Unit ships with a new Rust based CLI application "unitctl".
     +
    ++    *) Feature: the wasm-wasi-component language module now inherits the
    ++       processes environment.
    ++
     +    *) Change: under systemd unit runs in forking mode (once again).
     +
     +    *) Change: if building with njs, version 0.8.3 or later is now required.
```

**Review by avahahn — APPROVED** [review]

**Comment by Jcahilltorre** [comment]
Wondering, if this has to be merged when 1.33 releases, we can change the target branch to release-1.33 and merge it now. We will merge that branch to `main` at GA

**Comment by ac000** [comment]
> Wondering, if this has to be merged when 1.33 releases, we can change the target branch to release-1.33 and merge it now. We will merge that branch to `main` at GA

This is for the **unit** repository...

**Comment by ac000** [comment]
Add the unitctl 1.33.0 version update

**Comment by ac000** [comment]
Thanks @thresheek done!

**Comment by ac000** [comment]
```
$ git show --stat 5a647cd783f6bef7bb2769c914af55ae47d32f12
commit 5a647cd783f6bef7bb2769c914af55ae47d32f12
Author: Andrew Clayton <a.clayton@nginx.com>
Date:   Mon Sep 16 22:29:32 2024 +0100

    pkg/docker: Update dockerfiles
    
    Signed-off-by: Andrew Clayton <a.clayton@nginx.com>

 pkg/docker/Dockerfile.go1.21                            |  2 +-
 pkg/docker/Dockerfile.go1.22                            |  2 +-
 pkg/docker/Dockerfile.minimal                           |  2 +-
 pkg/docker/Dockerfile.node20                            |  2 +-
 pkg/docker/{Dockerfile.node21 => Dockerfile.node22}     |  4 ++--
 pkg/docker/Dockerfile.perl5.38                          |  2 +-
 pkg/docker/{Dockerfile.perl5.36 => Dockerfile.perl5.40} |  4 ++--
 pkg/docker/Dockerfile.php8.2                            |  2 +-
 pkg/docker/Dockerfile.php8.3                            |  2 +-
 pkg/docker/Dockerfile.python3.11                        |  2 +-
 pkg/docker/Dockerfile.python3.12                        |  2 +-
 pkg/docker/Dockerfile.ruby3.2                           |  2 +-
 pkg/docker/Dockerfile.ruby3.3                           |  2 +-
 pkg/docker/Dockerfile.wasm                              | 10 +++++-----
 14 files changed, 20 insertions(+), 20 deletions(-)
```

**Comment by ac000** [comment]
- Rebased with master
- Re-generated dockerfiles (this made the dockerfile version changes commit go-away...)

```
it show --stat 0f945165af5a933f6b2c62989249faec4a9cef52
commit 0f945165af5a933f6b2c62989249faec4a9cef52
Author: Andrew Clayton <a.clayton@nginx.com>
Date:   Mon Sep 16 22:29:32 2024 +0100

    pkg/docker: Update dockerfiles
    
    Signed-off-by: Andrew Clayton <a.clayton@nginx.com>

 pkg/docker/Dockerfile.go1.22                       |  6 +-
 .../{Dockerfile.go1.21 => Dockerfile.go1.23}       |  8 +-
 pkg/docker/Dockerfile.jsc11                        |  4 +-
 pkg/docker/Dockerfile.minimal                      |  6 +-
 pkg/docker/Dockerfile.node20                       |  6 +-
 .../{Dockerfile.node21 => Dockerfile.node22}       |  8 +-
 pkg/docker/Dockerfile.perl5.38                     |  6 +-
 .../{Dockerfile.perl5.36 => Dockerfile.perl5.40}   |  8 +-
 pkg/docker/Dockerfile.php8.2                       |  6 +-
 pkg/docker/Dockerfile.php8.3                       |  6 +-
 pkg/docker/Dockerfile.python3.11                   |  6 +-
 pkg/docker/Dockerfile.python3.11-slim              | 89 ++++++++++++++++++++++
 pkg/docker/Dockerfile.python3.12                   |  6 +-
 pkg/docker/Dockerfile.python3.12-slim              | 89 ++++++++++++++++++++++
 pkg/docker/Dockerfile.ruby3.2                      |  6 +-
 pkg/docker/Dockerfile.ruby3.3                      |  6 +-
 pkg/docker/Dockerfile.wasm                         | 14 ++--
 17 files changed, 229 insertions(+), 51 deletions(-)
```

**Review by thresheek — APPROVED** [review]
Yep, LGTM from Docker POV now.

**Comment by ac000** [comment]
Rebased with master.

**Pull request merged**
