### PR TITLE
fix #440 API change in PHP 8.0.0alpha1

### LINKED ISSUE #440: unit with php8.0 build break by https://github.com/php/php-src/pull/5676
https://github.com/php/php-src/pull/5676

ping  @remicollet ,can fix it ?

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by remicollet** [comment]
ping ?
(still apply for 8.0.0beta1)

**Comment by VBart** [comment]
Committed with a slight change. Thanks.

**Comment by khs1994** [comment]
@remicollet break by https://github.com/php/php-src/pull/6002

detail https://github.com/khs1994-docker/php/runs/1047307602?check_suite_focus=true#step:8:4461

**Comment by remicollet** [comment]
@khs1994 see pr #474

**Pull request closed without merging**
