### PR TITLE
Packaging update for 1.34.0 

### PR DESCRIPTION
**Pull request by thresheek**
No changes really, just a merge commit.

### CODE REVIEW

**Comment by thresheek** [comment]
Hmmm, I did fix a few conflicts here and there when creating the merge commit, but now GH says "this branch cannot be rebased due to conflicts" again.  @oxpa @ac000 do you remember if that was the same for https://github.com/nginx/unit/pull/1433 ?

**Comment by ac000** [comment]
I don't remember... maybe you'll just need to do it manually...

**Comment by thresheek** [comment]
And it looks I can just pull -ff locally just fine, so not sure what's hapenning here.

```
$ git clone https://github.com/nginx/unit unit-test-pull
Cloning into 'unit-test-pull'...
remote: Enumerating objects: 21968, done.
remote: Counting objects: 100% (3771/3771), done.
remote: Compressing objects: 100% (637/637), done.
remote: Total 21968 (delta 3275), reused 3151 (delta 3134), pack-reused 18197 (from 2)
Receiving objects: 100% (21968/21968), 12.64 MiB | 4.20 MiB/s, done.
Resolving deltas: 100% (16219/16219), done.

$ cd unit-test-pull
$ git checkout -b packaging origin/packaging
branch 'packaging' set up to track 'origin/packaging'.
Switched to a new branch 'packaging'

$ git remote add thresheek https://github.com/thresheek/unit

$ git pull thresheek packaging-1.34
remote: Enumerating objects: 1305, done.
remote: Counting objects: 100% (1092/1092), done.
remote: Compressing objects: 100% (346/346), done.
remote: Total 696 (delta 477), reused 500 (delta 346), pack-reused 0 (from 0)
Receiving objects: 100% (696/696), 113.44 KiB | 621.00 KiB/s, done.
Resolving deltas: 100% (477/477), completed with 94 local objects.
From https://github.com/thresheek/unit
 * branch              packaging-1.34 -> FETCH_HEAD
 * [new branch]        packaging-1.34 -> thresheek/packaging-1.34
Updating 624debcf..d8acad35
Fast-forward
```

**Comment by thresheek** [comment]
I can do a push manually, no biggie - please LGTM it then so we are formally following The Process 😃

**Comment by callahad** [comment]
Yeah, lgtm; the head of `packaging` should end up as d8acad350a52a20918c46c09cb0a0f5479400923

**Review by oxpa — APPROVED** [review]
LGTM, seem like a valid rebase, really.

**Comment by thresheek** [comment]
Yeah, looks manual push worked and autoclosed this PR.  Thanks!

**Pull request merged**
