### PR TITLE
Style.

### PR DESCRIPTION
**Pull request by andrey-zelenkov**

### CODE REVIEW

**Review by danielledeleo — APPROVED** [review]
LGTM. "White space formatting fixes" would also work as commit message :^)

**Comment by ac000** [comment]
You can have my

```
Reviewed-by: Andrew Clayton <a.clayton@nginx.org>
```

if you adjust the commit summary as suggested...

**Comment by andrey-zelenkov** [comment]
> Reviewed-by: Andrew Clayton <a.clayton@nginx.org>

Could you please check this one? I have never seen `@nginx.org` before, only `@nginx.com`

**Comment by ac000** [comment]
On Mon, 15 Jan 2024 14:01:45 -0800
andrey-zelenkov ***@***.***> wrote:

> > Reviewed-by: Andrew Clayton ***@***.***>  
> 
> Could you please check this one? I have never seen ***@***.***` before, only ***@***.***`
> 

Ugh, yes, should be .com sorry.

**Review by hongzhidao — APPROVED** [review]

**Pull request closed without merging**
