### PR TITLE
Docker-related updates

### PR DESCRIPTION
**Pull request by thresheek**
A few docker-related changes:
- Moved debian-based images to Bookworm
- Node and perl versions are updated to the latest
- Rust/rustup used for wasm variant are updated to the latest

### CODE REVIEW

**Review by ac000 — COMMENTED** [review]
I think we should set @costasd as the author for this patch, `Docker: moved to bookworm`

Original patch below...

```
From 3c3d067c8604225dc7c007d3941a2640199acd96 Mon Sep 17 00:00:00 2001
From: Costas Drongos <costas@inter.link>
Date: Fri, 22 Mar 2024 12:00:56 +0100
Subject: [PATCH] Docker: Bump containers to bookworm

---
 pkg/docker/Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/pkg/docker/Makefile b/pkg/docker/Makefile
index d8c530213..fb2615db3 100644
--- a/pkg/docker/Makefile
+++ b/pkg/docker/Makefile
@@ -10,7 +10,7 @@ PATCHLEVEL ?= 1
 
 MODULES ?= go jsc node perl php python ruby wasm
 
-VARIANT ?= bullseye
+VARIANT ?= bookworm
 
 VERSIONS_minimal ?=
 CONTAINER_minimal ?= debian:$(VARIANT)-slim
```

**Comment by ac000** [comment]
Or we can simply merge his [PR](https://github.com/nginx/unit/pull/1196)...

**Comment by thresheek** [comment]
Oh, we should just merge their PR of course.

**Comment by thresheek** [comment]
Rebased to include patch from #1196

**Review by ac000 — APPROVED** [review]

**Pull request merged**
